# Generated by Django 6.0.6 on 2026-06-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('license', 'License'), ('permit', 'Permit'), ('insurance', 'Insurance'), ('certificate', 'Certificate'), ('contract', 'Contract')], max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('responsible_person', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='compliance_docs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='accounts.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatApp')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('compliance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='compliance.complianceitem')),
            ],
        ),
    ]
