# Generated by Django 5.2.6 on 2026-09-05 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_complianceitem_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_issue_date', models.DateField()),
                ('old_expiry_date', models.DateField()),
                ('new_issue_date', models.DateField()),
                ('new_expiry_date', models.DateField()),
                ('old_daocument', models.FileField(blank=True, null=True, upload_to='compliance_renewals/old/')),
                ('new_document', models.FileField(blank=True, null=True, upload_to='compliance_renewals/new/')),
                ('compliance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='compliance.complianceitem')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_renewals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
