# Generated by Django 5.2.6 on 2026-09-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancerenewal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancerenewal',
            old_name='old_daocument',
            new_name='old_document',
        ),
    ]
