# Generated by Django 5.2.6 on 2026-09-07 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_rename_old_daocument_compliancerenewal_old_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerenewal',
            name='renewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
