# Generated by Django 5.2.6 on 2026-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('email_sent', 'Email Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('email_failed', 'Email Failed'), ('whatsapp_failed', 'WhatsApp Failed')], max_length=30),
        ),
    ]
