# Generated by Django 5.2.6 on 2026-08-06 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_activity_activity_type'),
        ('compliance', '0002_complianceitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='compliance_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='compliance.complianceitem'),
        ),
    ]
